### PR TITLE
Fix Position regression

### LINKED ISSUE #3: Accomodate to cc-engine-go changes
Hi there.

Just noticed that with [this change](https://github.com/codeclimate/cc-engine-go/commit/ea79ed8ba4d752e221273971a90d371a8bbcb0b3), [this](https://github.com/codeclimate-community/codeclimate-govet/blob/787431200d9a3f533b53125bf5573065edad48a8/codeclimate-govet.go#L67) won't work anymore, but should read

``` patch
diff --git a/codeclimate-govet.go b/codeclimate-govet.go
index 72ace1c..dd52d77 100644
--- a/codeclimate-govet.go
+++ b/codeclimate-govet.go
@@ -66,7 +66,7 @@ func main() {
                                                Categories:        []string{"Bug Risk"},
                                                Location: &engine.Location{
                                                        Path: strings.SplitAfter(path, rootPath)[1],
-                                                       Lines: &engine.Position{
+                                                       Lines: &engine.LinesOnlyPosition{
                                                                Begin: lineNo,
                                                                End:   lineNo,
                                                        },
```

Refrained from PRing because I don't know how to handle the binaries in this repo...

Thanks for the platform!
Stephan

### PR DESCRIPTION
**Pull request by srenatus**
Fixes #3. TODO update binaries (?)

### CODE REVIEW

**Comment by srenatus** [comment]
CI can't work in PRs since if it did, I might see your secrets [by changing this line](https://github.com/codeclimate-community/codeclimate-govet/blob/master/circle.yml#L10)...

**Comment by gdiggs** [comment]
@srenatus thanks! There are instructions for building the binaries in the README. Don't worry about the CI - it's something we still need to figure out. You do make a good point about that line...

**Comment by srenatus** [comment]
@GordonDiggs there's a twin [here](https://github.com/codeclimate-community/codeclimate-gofmt/blob/master/codeclimate-gofmt.go#L57), I'm afraid...

**Comment by srenatus** [comment]
@GordonDiggs this way of handling binaries seems a little odd. Couldn't the CI build them when creating the docker image?

**Comment by wfleming** [comment]
@srenatus thanks for this, and sorry for the delay in releasing. We've fixed the build process to be an automatic part of CI, and rolled this fix into that work on #6 (since we're not versioning our dependencies right now, there's not a great way to do this separately). Thanks again for bringing this up.

**Pull request closed without merging**
